Contributing.md
UniAuth/.github pull request #10
Opened 2021-02-24 19:39 UTC by kdsinghcoder

# Issue Related with PR
- fixes #3 

# Proposed Changes
- Change 1
- Change 2

# Additional info if necessary
- any additional information

# Checklist
- [x] Tests
- [x] Resolve Conflicts

# Screenshots

Original    |   Updated
:----------------: | :----------------:
** Original SS ** | ** Updated SS **

2021-02-25 02:39 UTC, YashKumarVerma requested changes

2021-02-25 02:39 UTC, YashKumarVerma commented on .github/CONTRIBUTING.md
> +[This is an example](http://stackoverflow.com/q/12488905/180626) of a bug report I wrote, and I think it's not a bad model. Here's [another example from Craig Hockenberry](http://www.openradar.me/119
avoid using personal pronouns like `I` in this

2021-02-25 02:39 UTC, YashKumarVerma commented on .github/CONTRIBUTING.md
> +  - Give sample code if you can. [My stackoverflow question](http://stackoverflow.com/q/12488905/180626) includes sample code that *anyone* with a base R setup can run to reproduce what I was seeing
same, avoid MY

2021-02-26 09:17 UTC, kdsinghcoder reviewed
@YashKumarVerma fixed as per requirement
.

2021-02-28 18:08 UTC, merged

2021-02-28 18:08 UTC, YashKumarVerma commented
thanks !