Added hound config file
UniAuth/.github pull request #9
Opened 2021-02-24 19:24 UTC by MASTERCHIEF011

Fixes #5

2021-02-24 19:25 UTC, MASTERCHIEF011 commented
is there any custom config for eslint that should be included?

2021-02-25 02:40 UTC, YashKumarVerma requested changes
please enable js

2021-02-25 02:57 UTC, MASTERCHIEF011 commented on .hound.yml
> +  enabled: false
Sorry I overlooked that.

2021-02-25 03:52 UTC, YashKumarVerma commented
add support for eslint / tslint checks

2021-02-25 16:16 UTC, YashKumarVerma approved these changes

2021-02-28 18:08 UTC, YashKumarVerma approved these changes

2021-02-28 18:09 UTC, merged

2021-02-28 18:09 UTC, YashKumarVerma commented
thanks !